-- AlterTable
ALTER TABLE "Route" ADD COLUMN     "hasWebhook" BOOLEAN NOT NULL DEFAULT true,
ALTER COLUMN "attributes" DROP NOT NULL,
ALTER COLUMN "method" DROP NOT NULL,
ALTER COLUMN "url" DROP NOT NULL;
